[project]
name = "osrs-voiceover-generator"
version = "0.1.0"
description = "generates voice over files by scrapping the osrs wiki for quest transcripts, and using the Elevenlabs SDK to generate voiceovers for them."
authors = ["Kevin Orel Edry <techg9@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[dependencies]
python = ">=3.12,<3.13"
ffmpeg = "*"

[pypi-dependencies]
elevenlabs = ">=1.3.1"
pydub = ">=0.25.1"
beautifulsoup4 = ">=4.12.3"
requests = ">=2.32.3"
ffmpeg-python = ">=0.2.0"
prompt-toolkit = ">=3.0.47"
tqdm = ">=4.66.4"
python-dotenv = ">=1.0.1"
fastapi = ">=0.115.0"
uvicorn = ">=0.32.0"

[tasks]
cli = "python cli-main.py"
server = "python -m voiceover_cli.server"
