blank_issues_enabled: true
contact_links:
  - name: OSRS Wiki Quest Transcripts
    url: https://oldschool.runescape.wiki/w/Category:Quest_transcript
    about: Find quest transcripts for your request on the OSRS Wiki
